### ISSUE TITLE
Strange symbol in README

### ISSUE THREAD

**Issue by Semigradsky** [isRuslan/awesome-elm#1]
In Chrome:
![image](https://cloud.githubusercontent.com/assets/1198848/7680404/df72f722-fd6e-11e4-82a3-46b459997c71.png)

In Firefox and IE all good:
![image](https://cloud.githubusercontent.com/assets/1198848/7680441/46bc5da6-fd6f-11e4-8fe6-755a79ee0148.png)

**Comment by isRuslan** [comment]
Set in hexadecimal form as `&#x2B06;` in [this](https://github.com/isRuslan/awesome-elm/commit/319c798ad247eab456197a931a5d4d2033696e33) commit.
Check it out, please.

**Comment by Semigradsky** [comment]
Looks like Google Chrome issue on Windows.
https://github.com/primer/markdown/issues/49
Thanks anyway!

**Comment by isRuslan** [comment]
Hope :arrow_up: will fix it. Windows-Chrome users are very important :)

**Comment by Semigradsky** [comment]
:+1:
