### ISSUE TITLE
Records from live coding

### ISSUE THREAD

**Issue by gasperz** [isRuslan/awesome-elm#103]
I would like to add at least two youtube links to Video section (or maybe separate section LiveCoding).
https://www.youtube.com/channel/UCJt-EkypIn-HoxNhoHqXmIA (Greg Ziegan)
https://www.youtube.com/channel/UCIl-0GHmn7gV3movEccOMRQ (Aaron VoderHaar).

I can create PR if you think that this could be added. It is helping me a lot learning Elm language.

br,
gapa

**Comment by isRuslan** [comment]
Hi @galtenberg they will perfectly fit in Video section, feel free to make a PR for this 👍
