### ISSUE TITLE
Several dead and outdated links

### ISSUE THREAD

**Issue by eboCode** [isRuslan/awesome-elm#159]
The first of the links in the Examples section, titled **'Official list - Examples from basic to big-project in official website.,'** seems to be to a page full of dead links (almost 30 of them). I've noticed this too on a visit probably a few months ago. One of my browsers, Firefox Dev Edition, gives this error on opening any of the linked pages:

> "Hmm. We’re having trouble finding that site.
> We can’t connect to the server at try.elm-lang.org."

Maybe it's time to disable this link or completely remove it?

**Comment by eboCode** [comment]
Found another outdated link under ’Learn,‘ titled ’Start app - Make an app, start it up.‘ It's been archived and marked ’Deprecated’ by its owner, evancz.

**Comment by isRuslan** [comment]
@eboCode Hello and thanks for pointing this out. You may feel free to contribute and remove dead link 👍

**Comment by eboCode** [comment]
NP, @isRuslan, please check PR #165.

The content at the Start App link now seems updated from what I saw back in 9/29/18, so I left that in place.

The Official List link now has a actual (non-404) page explaining why the examples are no longer live, but it just sort of suggests you try the Official Guide (with a large button) instead, which's already in the awesome list.

I searched the README.md for any other links to the 'Try Elm' site, and got one in the Misc. section, which I also removed, and another url with 'try' in it [Debug Elm](http://debug.elm-lang.org/try) that leads to a server not found error, so I removed it as well.

**Comment by isRuslan** [comment]
@eboCode Thanks!
