### ISSUE TITLE
IO is deprecated

### ISSUE THREAD

**Issue by sotojuan** [isRuslan/awesome-elm#16]
From the IO [README](https://github.com/maxsnew/IO/blob/master/README.md):

> This project is deprecated in favor of [elm-console](https://github.com/laszlopandy/elm-console).

**Comment by isRuslan** [comment]
Thanks, updated in [libs: add elm-console](https://github.com/isRuslan/awesome-elm/commit/fecb4d44a429f7a877ac85aa1e6550bfe61a0541)!
