### ISSUE TITLE
@jschomay Elm Narrative Engine v0.19

### ISSUE THREAD

**Issue by nelsonic** [isRuslan/awesome-elm#163]
Just came across @jschomay **`elm-narrative-engine`**: 
https://github.com/jschomay/elm-narrative-engine 
Looks like a good example project, recently updated to v.0.19
Worth adding a link to it? 🤔

**Comment by jschomay** [comment]
Honored to be considered for the list!

**Comment by nelsonic** [comment]
I feel this should be considered for the Examples section as it has a working example: http://elmnarrativeengine.com
And by _reading_ the example people can build their own narrative based apps (_e.g. chose your own adventure game_) which is a _great_ way to learn programming in _general_ and `Elm` specifically! 

@isRuslan if you have no objections, I will add it as:

```
* [Elm Narrative Engine](https://github.com/jschomay/elm-narrative-engine) - A framework 
for building interactive fiction style stories in Elm. Detailed example [elmnarrativeengine.com](http://elmnarrativeengine.com) 
shows how to build a "chose your own adventure" (story) game; perfect for beginners. **Elm v.0.19**
```

**Comment by nelsonic** [comment]
@isRuslan please see PR: #164 (_thanks again for this great repo/resource!_)

**Comment by isRuslan** [comment]
Thank you, #164 is merged 👍

**Comment by nelsonic** [comment]
@isRuslan thanks! 🎉
