### ISSUE TITLE
Seeds (Game)

### ISSUE THREAD

**Issue by nelsonic** [isRuslan/awesome-elm#166]
Hi @isRuslan! Hope your weekend is going well.

While going through the list of examples, I noticed that @andrewMacmurray's Seeds game is not listed.
+ Complete source code: https://github.com/andrewMacmurray/seeds-game 
+ Play Online: https://www.seedsgame.com

Andrew recently updated the game to **Elm 0.19** and it even has _tests_!
I feel this Example App/Game is worthy of inclusion in the Examples list as it's a legitimately great game!

If you have no objections, I will PR the inclusion so other people can _discover_ this awesomeness! 🌱

**Comment by nelsonic** [comment]
Pull Request: https://github.com/isRuslan/awesome-elm/pull/169

**Comment by isRuslan** [comment]
Thanks!
