### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by razzeee** [isRuslan/awesome-elm#171]
Hey @isRuslan 

are you still willing and having time to maintain this?
No disrespect, just curious what the future of this project is, we all know how it is, sometimes life changes and you need spend you time in other communities :)

**Comment by isRuslan** [comment]
Hi @Razzeee! Thanks for your concern.
Yes, I have less time to maintain this project than I used to. So, I think it is time to find a new maintainer.
I opened the separate issue about it #172 
If you personally  interested, please follow the description.

Thanks!
