### ISSUE TITLE
Elm articles

### ISSUE THREAD

**Issue by Oxyrus** [isRuslan/awesome-elm#48]
Here are some articles written by @Diamond

[Getting started with Elm](https://medium.com/p/11d7a53b1a78)
[Understanding Elm: Signals, Mailboxes, Adresses, and Actions](https://medium.com/p/7932781396ef)
[Setting up Elm with Phoenix](https://medium.com/p/be3a9f55bac2)

**Comment by isRuslan** [comment]
Nice ones, thank you :+1: 
I would like to add **Getting started with Elm** to article section. @Oxyrus will you make a PR for this article?

**Comment by Oxyrus** [comment]
Feel free to add them yourself :)

**Comment by isRuslan** [comment]
Added.
