### ISSUE TITLE
Search by topic e.g. "recursion"

### ISSUE THREAD

**Issue by ghost** [isRuslan/awesome-elm#71]
After doing Learn You An Elm's chapter on recursion, I'd like to practise some recursion, so I came here to find some resources, but searching the page for "recursion" returned 0 results. I'd be happy to start this process by e.g. creating a file of keywords for Learn You An Elm and start with "recursion", so I could find it by searching the repository.

**Comment by isRuslan** [comment]
Hi, @willnwhite, I'd love to have such tag-system to search through. But I don not think it will be suitable in markdown format, tags + link will clutter in one page.
Awesome-elm is more general resource, not only learning helpers/links.

I also going to create a more interactive format of this list - a web page, where we could search, group and share link in more convenient way. Maybe there will be a place for link tags.
Bwt, thanks for noticing, I'll ping you when I come up with how to create such page and you can contribute by tagging resources.

**Comment by ghost** [comment]
Hi. Cluttering the main page with tags could be avoided by putting them in a separate file. A dedicated website sounds like the best solution, but in the meantime you could search this repo for the search term, and be collecting tags as people find them. https://github.com/isRuslan/awesome-elm/pull/73
